language: node_js
node_js:
- node
cache: npm
install: true
jobs:
  include:
  - stage: build and deploy
    if: tag IS present
    script:
    - npm i
    - npm i -g now
    - npm run deploy
    - npm run alias
env:
  global:
  - secure: QtI2vy3TydlPERmplV6F7jbUCWcZJW5miV1997gZ8T2RE5nvhOvEPhMcfhJ+OLWxOJEWs/Z0CciJ18BoB6qn+SWjuIeR+UX+u9hFbRtAArQkQM0XbuhwqsTGjy18jEKRtldMAAE9tW9cxyy+s9+SiBAtXJNY0BMYk092X1KmI4rZM5v0GmuMTbyGtlGrb2XT0YVz/LJIdiJVI9opHl/8hkKYf/ku6+FPa9ziO8gw7sa0/y9GNQvA0/z4Pt+ZFhwOKzIO2s7W4CNPUOfDDom5gVL0yi4+EkWj4MlsgwgZuUb50AeVQBngHPx4ydISITJ+H/EeFKLK/SdH87kQRj+ek310IenTMZoBeL6sZ66cTijm2ssLZcJannurd7DWkdHG5CIx1BzNgMRV4buELiudRovC31iYUCDrAE0wTSdikSLRLAjvqOqHlmHXerFMS4e1iGt7+B2FGfwQSpU3IkK3z7dlarc8iVziFAMfP9+fGbi7lU6arMd11T7U/jormua/1Wl1hWjcamp5YPJQzjI802EtRorJIW8JfJPWX83UDdGEKjN7y1p3ZSEAHVxLAYN1flLdnTsCfQxc4DmJCRgCfuXBzHUQzSg/I7ipWg3OSxBI242xFWMds644WvjeQYgDAS3AbpKkBDypm8PZwZMPlViXbDZjz22zhP3Lm4BPElI=
